export type MockReviewArticle = {
  id: string;
  headline: string;
  publication: string | null;
  publishedDate: Date | null;
  url: string;
  sourceType: string | null;
  rawHtml?: string | null;
  extractedText?: string | null;
  extractedExcerpt?: string | null;
  extractionMethod?: string | null;
  bodyFetchStatus?: string | null;
  bodyFetchError?: string | null;
  bodyFetchedAt?: Date | null;
  robotsAllowed?: boolean | null;
  paywallLikely?: boolean | null;
  sourceReliability?: string | null;
  needsReview?: boolean;
  extractionStatus: string;
  extractionMode?: string | null;
  suspectedCategory: string | null;
  confidenceScore: number | null;
  summary: string | null;
  linkedProjectId: string | null;
  linkedProjectTitle: string | null;
  linkedShowId: string | null;
  linkedShowTitle: string | null;
  extractedProjectTitle: string | null;
  extractedFormat: string | null;
  extractedGenre?: string | null;
  extractedSourceMaterial?: string | null;
  extractedStatus: string | null;
  extractedLogline: string | null;
  extractedBuyer: string | null;
  extractedStudio: string | null;
  extractedCompanies: string | null;
  extractedPeople: string | null;
  extractedCountry: string | null;
  extractedIsAcquisition?: boolean | null;
  extractedIsCoProduction?: boolean | null;
  extractedIsInternational?: boolean | null;
  extractedAnnouncementDate: Date | null;
  extractedPremiereDate: Date | null;
  extractedRelationships: string | null;
  extractedFieldsNeedingReview?: string | null;
  extractedDeduplicationNotes?: string | null;
  extractedStructuredDataJson?: unknown;
  aiExtractionError?: string | null;
};

export const mockReviewArticles: MockReviewArticle[] = [
  {
    id: "mock-article-1",
    headline: "Netflix lands coastal crime drama Harbor Lights",
    publication: "Deadline",
    publishedDate: new Date("2026-04-21T12:00:00.000Z"),
    url: "https://preview.example.com/harbor-lights",
    sourceType: "rss_placeholder",
    rawHtml: "<article><p>Netflix landed Harbor Lights from A24 Television and wiip with Maya Rivers and Noor Hassan attached.</p></article>",
    extractedText:
      "Netflix landed Harbor Lights from A24 Television and wiip with Maya Rivers and Noor Hassan attached. The package centers on a coastal medical examiner uncovering a port corruption conspiracy.",
    extractedExcerpt: "Netflix landed Harbor Lights from A24 Television and wiip with Maya Rivers and Noor Hassan attached.",
    extractionMethod: "mock_readability",
    bodyFetchStatus: "success",
    bodyFetchError: null,
    bodyFetchedAt: new Date("2026-04-28T12:00:00.000Z"),
    robotsAllowed: true,
    paywallLikely: false,
    sourceReliability: "high",
    extractionStatus: "Needs Review",
    extractionMode: "mock",
    suspectedCategory: "Sale",
    confidenceScore: 0.89,
    summary: "A coastal crime package starring a forensic lead character lands at Netflix with premium studio support.",
    linkedProjectId: "mock-project-harbor-lights",
    linkedProjectTitle: "Harbor Lights",
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Harbor Lights",
    extractedFormat: "One-hour drama",
    extractedStatus: "sold",
    extractedLogline: "A coastal medical examiner uncovers a shipping conspiracy while rebuilding ties with her hometown.",
    extractedBuyer: "Netflix",
    extractedStudio: "A24 Television",
    extractedCompanies: "wiip",
    extractedPeople: "Maya Rivers, Noor Hassan",
    extractedCountry: "United States",
    extractedAnnouncementDate: new Date("2026-04-21T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "Netflix <-> A24 Television <-> wiip <-> Maya Rivers",
    extractedFieldsNeedingReview: "production companies, talent billing",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-2",
    headline: "BBC boards Northern Exchange co-production",
    publication: "The Hollywood Reporter",
    publishedDate: new Date("2026-04-24T12:00:00.000Z"),
    url: "https://preview.example.com/northern-exchange",
    sourceType: "manual_url",
    rawHtml: null,
    extractedText: null,
    extractedExcerpt: null,
    extractionMethod: null,
    bodyFetchStatus: "robots_blocked",
    bodyFetchError: "robots.txt disallows body fetch for this URL.",
    bodyFetchedAt: new Date("2026-04-28T12:00:00.000Z"),
    robotsAllowed: false,
    paywallLikely: false,
    sourceReliability: "high",
    extractionStatus: "Approved",
    extractionMode: "mock",
    suspectedCategory: "Co-Production",
    confidenceScore: 0.94,
    summary: "An international thriller package firms up with BBC, Universal Television, and Bad Wolf.",
    linkedProjectId: "mock-project-northern-exchange",
    linkedProjectTitle: "Northern Exchange",
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Northern Exchange",
    extractedFormat: "Drama series",
    extractedStatus: "series_order",
    extractedLogline: "A London fixer and Toronto prosecutor collide on a politically explosive extradition case.",
    extractedBuyer: "BBC",
    extractedStudio: "Universal Television",
    extractedCompanies: "Bad Wolf",
    extractedPeople: "Lena Ortiz, Graham Pike",
    extractedCountry: "United Kingdom",
    extractedAnnouncementDate: new Date("2026-04-24T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "BBC <-> Universal Television <-> Bad Wolf",
    extractedFieldsNeedingReview: "territory split",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-3",
    headline: "Apple TV+ develops Red Valley adaptation",
    publication: "Variety",
    publishedDate: new Date("2026-03-31T12:00:00.000Z"),
    url: "https://preview.example.com/red-valley",
    sourceType: "rss_placeholder",
    rawHtml: "<html><body><div>Subscribe to continue reading Red Valley rights details.</div></body></html>",
    extractedText: null,
    extractedExcerpt: "Paywall likely. Only partial teaser content was available.",
    extractionMethod: "mock_paywall_detection",
    bodyFetchStatus: "paywall_likely",
    bodyFetchError: "Paywall likely; body text was not stored.",
    bodyFetchedAt: new Date("2026-04-28T12:00:00.000Z"),
    robotsAllowed: true,
    paywallLikely: true,
    sourceReliability: "high",
    extractionStatus: "New",
    extractionMode: "mock",
    suspectedCategory: "Acquisition",
    confidenceScore: 0.73,
    summary: "The project appears to be an English-language remake based on an international western format.",
    linkedProjectId: null,
    linkedProjectTitle: null,
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Red Valley",
    extractedFormat: "Drama series",
    extractedStatus: "in_development",
    extractedLogline: "A Spanish neo-western format is packaged for an English-language adaptation.",
    extractedBuyer: "Apple TV+",
    extractedStudio: "A24 Television",
    extractedCompanies: "Tomorrow Studios",
    extractedPeople: "Rina Sato, Caleb Stone",
    extractedCountry: "Spain",
    extractedAnnouncementDate: new Date("2026-03-31T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "Apple TV+ acquires remake rights with Tomorrow Studios producing",
    extractedFieldsNeedingReview: "buyer attachment, underlying rights holder",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-4",
    headline: "Caleb Stone joins HBO package The Witness Chair",
    publication: "TheWrap",
    publishedDate: new Date("2026-03-08T12:00:00.000Z"),
    url: "https://preview.example.com/witness-chair",
    sourceType: "rss_placeholder",
    rawHtml: null,
    extractedText: null,
    extractedExcerpt: null,
    extractionMethod: null,
    bodyFetchStatus: "timeout",
    bodyFetchError: "Timed out while fetching article HTML.",
    bodyFetchedAt: new Date("2026-04-28T12:00:00.000Z"),
    robotsAllowed: true,
    paywallLikely: false,
    sourceReliability: "medium",
    extractionStatus: "Rejected",
    extractionMode: "mock",
    suspectedCategory: "Talent Attachment",
    confidenceScore: 0.66,
    summary: "The item is probably relevant, but details are too thin and need editorial judgment.",
    linkedProjectId: "mock-project-witness-chair",
    linkedProjectTitle: "The Witness Chair",
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "The Witness Chair",
    extractedFormat: "Limited series",
    extractedStatus: "pilot_order",
    extractedLogline: "A famous actor becomes the key witness in a case that reopens a studio-era disappearance.",
    extractedBuyer: "HBO",
    extractedStudio: "Warner Bros. Television",
    extractedCompanies: "A24 Television",
    extractedPeople: "Lena Ortiz, Caleb Stone",
    extractedCountry: "United States",
    extractedAnnouncementDate: new Date("2026-03-07T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "Caleb Stone joins Lena Ortiz package",
    extractedFieldsNeedingReview: "lead role specificity",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-5",
    headline: "Harbor Lights sale item repeated by follow-up brief",
    publication: "TVLine",
    publishedDate: new Date("2026-04-22T12:00:00.000Z"),
    url: "https://preview.example.com/harbor-lights-duplicate",
    sourceType: "rss_placeholder",
    rawHtml: null,
    extractedText: null,
    extractedExcerpt: null,
    extractionMethod: null,
    bodyFetchStatus: "fetch_error",
    bodyFetchError: "Fetch failed with 502.",
    bodyFetchedAt: new Date("2026-04-28T12:00:00.000Z"),
    robotsAllowed: true,
    paywallLikely: false,
    sourceReliability: "medium",
    extractionStatus: "Duplicate",
    extractionMode: "mock",
    suspectedCategory: "Sale",
    confidenceScore: 0.51,
    summary: "A near-duplicate brief with minimal net-new information compared with the original report.",
    linkedProjectId: "mock-project-harbor-lights",
    linkedProjectTitle: "Harbor Lights",
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Harbor Lights",
    extractedFormat: "One-hour drama",
    extractedStatus: "sold",
    extractedLogline: "A coastal medical examiner uncovers a shipping conspiracy while rebuilding ties with her hometown.",
    extractedBuyer: "Netflix",
    extractedStudio: "A24 Television",
    extractedCompanies: "wiip",
    extractedPeople: "Maya Rivers",
    extractedCountry: "United States",
    extractedAnnouncementDate: new Date("2026-04-22T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "Likely duplicate of prior Harbor Lights sale item",
    extractedFieldsNeedingReview: "duplicate confirmation",
    extractedDeduplicationNotes: "Matches Harbor Lights sale item on title, buyer, and date proximity."
  },
  {
    id: "mock-article-6",
    headline: "ABC gives The Family Ledger a pilot order from 20th Television",
    publication: "Deadline",
    publishedDate: new Date("2026-02-11T12:00:00.000Z"),
    url: "https://preview.example.com/family-ledger-pilot",
    sourceType: "rss_placeholder",
    rawHtml: null,
    extractedText: null,
    extractedExcerpt: null,
    extractionMethod: null,
    bodyFetchStatus: "not_fetched",
    bodyFetchError: null,
    bodyFetchedAt: null,
    robotsAllowed: null,
    paywallLikely: false,
    sourceReliability: "high",
    extractionStatus: "New",
    extractionMode: "mock",
    suspectedCategory: "Pilot Order",
    confidenceScore: 0.84,
    summary: "A broadcast family drama receives a pilot order at ABC.",
    linkedProjectId: null,
    linkedProjectTitle: null,
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "The Family Ledger",
    extractedFormat: "Broadcast drama",
    extractedStatus: "pilot_order",
    extractedLogline: "A fractured family discovers their inheritance is tied to solving an old town scandal.",
    extractedBuyer: "ABC",
    extractedStudio: "20th Television",
    extractedCompanies: "wiip",
    extractedPeople: "Marcus Bell",
    extractedCountry: "United States",
    extractedAnnouncementDate: new Date("2026-02-11T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "ABC <-> 20th Television <-> Marcus Bell",
    extractedFieldsNeedingReview: "casting, pilot presentation date",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-7",
    headline: "Peacock picks up unscripted format Second Chance Kitchen to series",
    publication: "Variety",
    publishedDate: new Date("2026-03-05T12:00:00.000Z"),
    url: "https://preview.example.com/second-chance-kitchen",
    sourceType: "rss_placeholder",
    rawHtml: "<article><p>Peacock has given a straight-to-series order to Second Chance Kitchen from Universal Television and Left/Right, executive produced by Priya Raman.</p></article>",
    extractedText:
      "Peacock has given a straight-to-series order to Second Chance Kitchen from Universal Television and Left/Right, executive produced by Priya Raman.",
    extractedExcerpt: "Peacock has given a straight-to-series order to Second Chance Kitchen from Universal Television and Left/Right.",
    extractionMethod: "mock_readability",
    bodyFetchStatus: "success",
    bodyFetchError: null,
    bodyFetchedAt: new Date("2026-04-28T12:00:00.000Z"),
    robotsAllowed: true,
    paywallLikely: false,
    sourceReliability: "high",
    extractionStatus: "Needs Review",
    extractionMode: "mock",
    suspectedCategory: "Series Pickup",
    confidenceScore: 0.86,
    summary: "Peacock commits a food-competition format to series.",
    linkedProjectId: null,
    linkedProjectTitle: null,
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Second Chance Kitchen",
    extractedFormat: "Unscripted format",
    extractedStatus: "series_order",
    extractedLogline: "Chefs revisit signature failures for a second shot at national exposure.",
    extractedBuyer: "Peacock",
    extractedStudio: "Universal Television",
    extractedCompanies: "Left/Right",
    extractedPeople: "Priya Raman",
    extractedCountry: "United States",
    extractedAnnouncementDate: new Date("2026-03-05T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "Peacock <-> Universal Television <-> Left/Right",
    extractedFieldsNeedingReview: "episode order",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-8",
    headline: "Netflix sets June premiere for animated adventure Paper Kingdom",
    publication: "The Hollywood Reporter",
    publishedDate: new Date("2026-05-10T12:00:00.000Z"),
    url: "https://preview.example.com/paper-kingdom-premiere",
    sourceType: "rss_placeholder",
    rawHtml: null,
    extractedText: null,
    extractedExcerpt: null,
    extractionMethod: null,
    bodyFetchStatus: "not_fetched",
    bodyFetchError: null,
    bodyFetchedAt: null,
    robotsAllowed: null,
    paywallLikely: false,
    sourceReliability: "high",
    extractionStatus: "Needs Review",
    extractionMode: "mock",
    suspectedCategory: "Current Show",
    confidenceScore: 0.9,
    summary: "A premiere-date announcement for an animated project already in the pipeline.",
    linkedProjectId: null,
    linkedProjectTitle: null,
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Paper Kingdom",
    extractedFormat: "Animation series",
    extractedStatus: "airing",
    extractedLogline: "A young cartographer enters a folded paper world where maps change the laws of nature.",
    extractedBuyer: "Netflix",
    extractedStudio: "A24 Television",
    extractedCompanies: "Tomorrow Studios",
    extractedPeople: "Rina Sato",
    extractedCountry: "Japan",
    extractedAnnouncementDate: new Date("2026-05-10T12:00:00.000Z"),
    extractedPremiereDate: new Date("2026-06-12T12:00:00.000Z"),
    extractedRelationships: "Netflix platform launch for Paper Kingdom",
    extractedFieldsNeedingReview: "territory rollout",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-9",
    headline: "BBC and CBC develop Arctic Signal as international co-production",
    publication: "TheWrap",
    publishedDate: new Date("2026-04-02T12:00:00.000Z"),
    url: "https://preview.example.com/arctic-signal",
    sourceType: "rss_placeholder",
    extractionStatus: "New",
    extractionMode: "mock",
    suspectedCategory: "International",
    confidenceScore: 0.88,
    summary: "A northern thriller enters development as an international co-production.",
    linkedProjectId: null,
    linkedProjectTitle: null,
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "Arctic Signal",
    extractedFormat: "Drama series",
    extractedStatus: "in_development",
    extractedLogline: "A remote warning system exposes a political cover-up stretching across Arctic borders.",
    extractedBuyer: "BBC",
    extractedStudio: "Universal Television",
    extractedCompanies: "Bad Wolf",
    extractedPeople: "Graham Pike",
    extractedCountry: "Canada",
    extractedAnnouncementDate: new Date("2026-04-02T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "BBC <-> CBC <-> Bad Wolf co-production",
    extractedFieldsNeedingReview: "Canadian network partner",
    extractedDeduplicationNotes: null
  },
  {
    id: "mock-article-10",
    headline: "HBO renews South Pier as FX cancels Open Tabs",
    publication: "TVLine",
    publishedDate: new Date("2026-04-18T12:00:00.000Z"),
    url: "https://preview.example.com/renewal-cancellation-roundup",
    sourceType: "rss_placeholder",
    extractionStatus: "Needs Review",
    extractionMode: "mock",
    suspectedCategory: "Renewal",
    confidenceScore: 0.7,
    summary: "A two-item roundup includes one renewal and one cancellation.",
    linkedProjectId: null,
    linkedProjectTitle: null,
    linkedShowId: null,
    linkedShowTitle: null,
    extractedProjectTitle: "South Pier",
    extractedFormat: "Drama series",
    extractedStatus: "renewed",
    extractedLogline: "Waterfront corruption thriller returning for another season.",
    extractedBuyer: "HBO",
    extractedStudio: "Warner Bros. Television",
    extractedCompanies: "A24 Television",
    extractedPeople: "Lena Ortiz",
    extractedCountry: "United States",
    extractedAnnouncementDate: new Date("2026-04-18T12:00:00.000Z"),
    extractedPremiereDate: null,
    extractedRelationships: "South Pier renewed; Open Tabs cancellation noted in article body.",
    extractedFieldsNeedingReview: "secondary cancellation item requires split handling",
    extractedDeduplicationNotes: null
  }
];
