import type { CurrentTvRow } from "@/components/tables/current-tv-tracker";

export const mockCurrentShows: CurrentTvRow[] = [
  {
    id: "mock-city-desk",
    title: "City Desk",
    networkOrPlatform: "ABC",
    buyerHref: "/buyers/mock-abc",
    premiereDate: "2026-04-29T12:00:00.000Z",
    finaleDate: "2026-06-24T12:00:00.000Z",
    seasonNumber: 2,
    episodeCount: 10,
    status: "airing",
    genre: "Workplace Drama",
    studio: "20th Television",
    productionCompanies: "wiip",
    country: "United States",
    sourceType: "network_press",
    sourceReliability: "high",
    seasonType: "returning_series",
    premiereTime: "10:00 PM ET",
    episodeTitle: "The Tip Sheet",
    episodeNumber: 201,
    airPattern: "Wednesdays",
    verifiedAt: "2026-04-25T12:00:00.000Z",
    needsVerification: false,
    sourceUrl: "https://example.com/shows/city-desk",
    notes: "Mock preview record for the current TV tracker."
  },
  {
    id: "mock-crown-evidence",
    title: "Crown Evidence",
    networkOrPlatform: "BBC",
    buyerHref: "/buyers/mock-bbc",
    premiereDate: "2026-05-05T12:00:00.000Z",
    finaleDate: "2026-06-09T12:00:00.000Z",
    seasonNumber: 1,
    episodeCount: 6,
    status: "premiering soon",
    genre: "Crime",
    studio: "Universal Television",
    productionCompanies: "Bad Wolf",
    country: "United Kingdom",
    sourceType: "network_press",
    sourceReliability: "high",
    seasonType: "new_series",
    premiereTime: "9:00 PM BST",
    episodeTitle: "First Evidence",
    episodeNumber: 101,
    airPattern: "Tuesdays",
    verifiedAt: "2026-04-24T12:00:00.000Z",
    needsVerification: false,
    sourceUrl: "https://example.com/shows/crown-evidence",
    notes: "International crime drama preview item."
  },
  {
    id: "mock-food-court-kings",
    title: "Food Court Kings",
    networkOrPlatform: "Peacock",
    buyerHref: "/buyers/mock-peacock",
    premiereDate: "2026-05-15T12:00:00.000Z",
    finaleDate: "2026-07-10T12:00:00.000Z",
    seasonNumber: 2,
    episodeCount: 10,
    status: "returning",
    genre: "Food Competition",
    studio: "Universal Television",
    productionCompanies: "Left/Right",
    country: "United States",
    sourceType: "platform_press",
    sourceReliability: "high",
    seasonType: "returning_series",
    premiereTime: "8:00 PM ET",
    episodeTitle: "Kitchen Reopens",
    episodeNumber: 201,
    airPattern: "Fridays",
    verifiedAt: "2026-04-21T12:00:00.000Z",
    needsVerification: false,
    sourceUrl: "https://example.com/shows/food-court-kings",
    notes: "Returning unscripted competition series."
  },
  {
    id: "mock-signal-house",
    title: "Signal House",
    networkOrPlatform: "FX",
    buyerHref: "/buyers/mock-fx",
    premiereDate: "2026-02-20T12:00:00.000Z",
    finaleDate: "2026-04-30T12:00:00.000Z",
    seasonNumber: 1,
    episodeCount: 10,
    status: "finale soon",
    genre: "Spy Drama",
    studio: "20th Television",
    productionCompanies: "Tomorrow Studios",
    country: "United States",
    sourceType: "network_press",
    sourceReliability: "high",
    seasonType: "finale",
    premiereTime: "10:00 PM ET",
    episodeTitle: "Dead Drop",
    episodeNumber: 110,
    airPattern: "Thursdays",
    verifiedAt: "2026-04-27T12:00:00.000Z",
    needsVerification: true,
    sourceUrl: "https://example.com/shows/signal-house",
    notes: "Finale watch mock item."
  }
];
